# Generated by Django 5.2.3 on 2025-07-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='heure_fermeture',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='heure_ouverture',
        ),
    ]
