# Generated by Django 5.2.3 on 2025-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_salon_heure_fermeture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='jours_ouverture',
        ),
        migrations.AlterField(
            model_name='salon',
            name='nombre_employes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
