# Generated by Django 5.2.3 on 2025-07-21 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_salon_jours_ouverture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être entré au format: '+999999999'. Il peut inclure des espaces, des tirets ou des parenthèses. Minimum 7 chiffres, maximum 15.", regex='^\\+?[\\d\\s\\-\\(\\)]{7,15}$')]),
        ),
    ]
