# Generated by Django 5.2.3 on 2025-07-22 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_utilisateur_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soin',
            name='duree',
        ),
        migrations.AddField(
            model_name='soinsalondetail',
            name='duree',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
            preserve_default=False,
        ),
    ]
