# Generated by Django 5.2.3 on 2025-08-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='date_debut_periode',
            field=models.DateField(blank=True, null=True, verbose_name="Début de la période d'activité"),
        ),
        migrations.AddField(
            model_name='salon',
            name='date_fin_periode',
            field=models.DateField(blank=True, null=True, verbose_name="Fin de la période d'activité"),
        ),
    ]
